export enum CaseEditPageText {
  RESUMED_FORM_DISCARD = 'RESUMED_FORM_DISCARD',
  NEW_FORM_DISCARD = 'NEW_FORM_DISCARD',
  NEW_FORM_SAVE = 'NEW_FORM_CHANGED_SAVE',
  RESUMED_FORM_SAVE = 'RESUMED_FORM_SAVE',
  TRIGGER_TEXT_START = 'Continue',
  TRIGGER_TEXT_SAVE = 'Save and continue',
  TRIGGER_TEXT_CONTINUE = 'Ignore Warning and Continue'
}