export type FieldTypeEnum =
  'Text'
  | 'TextArea'
  | 'Postcode'
  | 'Number'
  | 'YesOrNo'
  | 'Date'
  | 'DateTime'
  | 'Email'
  | 'PhoneUK'
  | 'MoneyGBP'
  | 'FixedList'
  | 'DynamicList'
  | 'DynamicMultiSelectList'
  | 'FixedRadioList'
  | 'Complex'
  | 'Collection'
  | 'MultiSelectList'
  | 'Document'
  | 'Label'
  | 'AddressGlobal'
  | 'AddressGlobalUK'
  | 'AddressUK'
  | 'CasePaymentHistoryViewer'
  | 'CaseHistoryViewer'
  | 'Organisation';
