export enum EventStates {
  CHECK_FOR_MATCHING_TASKS = 'CHECK FOR MATCHING TASKS',
  NO_TASK = 'NO TASK',
  ONE_TASK = 'ONE TASK',
  MULTIPLE_TASK = 'MULTIPLE TASK',
  TASK_ASSIGNED_TO_USER = 'TASK ASSIGNED TO USER',
  TASK_UNASSIGNED = 'TASK UNASSIGNED',
  TASK_ASSIGNMENT_REQUIRED = 'TASK ASSIGNMENT REQUIRED',
  ASSIGN_TASK_TO_SELF = 'ASSIGN TASK TO SELF',
  ASK_MANAGER_TO_ASSIGN_TASK = 'ASK MANAGER TO ASSIGN TASK',
  SHOW_WARNING = 'SHOW WARNING',
  SHOW_ERROR_MESSAGE = 'SHOW ERROR MESSAGE',
  CANCEL = 'CANCEL'
}
