export enum EventStates {
  NO_TASK = 'NO TASK',
  ONE_TASK = 'ONE TASK',
  MULTIPLE_TASK = 'MULTIPLE TASK',
  TASK_ASSIGNED_TO_USER = 'TASK ASSIGNED TO USER',
  TASK_UNASSIGNED = 'TASK UNASSIGNED'
}
