export type FieldTypeEnum =
  'Text'
  | 'TextArea'
  | 'Postcode'
  | 'Number'
  | 'YesOrNo'
  | 'Date'
  | 'DateTime'
  | 'Email'
  | 'PhoneUK'
  | 'MoneyGBP'
  | 'FixedList'
  | 'DynamicList'
  | 'FixedRadioList'
  | 'DynamicRadioList'
  | 'Complex'
  | 'Collection'
  | 'MultiSelectList'
  | 'Document'
  | 'Label'
  | 'AddressGlobal'
  | 'AddressGlobalUK'
  | 'AddressUK'
  | 'CasePaymentHistoryViewer'
  | 'CaseHistoryViewer'
  | 'Organisation'
  | 'WaysToPay'
  | 'ComponentLauncher'
  | 'Flags'
  | 'FlagDetail'
  | 'FlagLauncher'
  | 'CaseFlag' // Temporary field type for faking Flags field type; to be removed
  | 'JudicialUserField'
  | 'MultipleDemoType'
  | 'LeadDemoType';
