export enum CaseFlagDisplayContextParameter {
  CREATE = '#ARGUMENT(CREATE)',
  CREATE_EXTERNAL = '#ARGUMENT(CREATE,EXTERNAL)',
  READ_EXTERNAL = '#ARGUMENT(READ,EXTERNAL)',
  UPDATE = '#ARGUMENT(UPDATE)',
  UPDATE_EXTERNAL = '#ARGUMENT(UPDATE,EXTERNAL)'
}
